[package]
name = "tenet-analyzer"
version.workspace = true
edition.workspace = true

[dependencies]
tenet-types.workspace = true
tenet-errors.workspace = true
tenet-config.workspace = true
tenet-database.workspace = true
tenet-web.workspace = true
tenet-stealth.workspace = true
tenet-wasm.workspace = true
tenet-browser.workspace = true
tenet-mobile.workspace = true
tokio.workspace = true
sqlx.workspace = true
reqwest.workspace = true
sha2.workspace = true
hex.workspace = true
futures-util.workspace = true
ulid.workspace = true
async-trait.workspace = true
tracing.workspace = true

[dev-dependencies]
base64.workspace = true

[lints]
workspace = true
